# Main settings
da_strat: 'mmd'
benchmark: 'dollarstreet'
source: 'developed'
target: 'developing'

# CNN details
cnn: 'ResNet50'
l2_normalize: false
temperature: 1.0

# Class-balanced sampling options
class_balance_source: true
pseudo_balance_target: false

# Training params
optimizer: 'SGD'
batch_size: 128
load_source: true
lr: 0.001
wd: 0.0005
num_epochs: 50

# DA params
load_da: false
da_lr: 0.001
da_wd: 0.0005
da_num_epochs: 100

# Loss weights
lambda_src: 1.0
lambda_unsup: 1.0

use_cuda: True