# Main settings
da_strat: 'sentry'
benchmark: 'dollarstreet'
source: 'developed'
target: 'developing'
use_lm: false
use_wiki: false

# CNN details
cnn: 'ResNet50'
l2_normalize: true
temperature: 0.05

# Class-balanced sampling options
class_balance_source: true
pseudo_balance_target: true

# Training params
optimizer: 'SGD'
batch_size: 128
load_source: true
lr: 0.001
wd: 0.0005
num_epochs: 50

# DA params
load_da: false
da_lr: 0.001
da_wd: 0.0005
da_num_epochs: 100

# Loss weights
lambda_src: 1.0
lambda_unsup: 0.1
lambda_infoent: 0.1

use_cuda: True